### ISSUE TITLE
Функция, которая говорит високосный год или нет

### ISSUE THREAD

**Issue by vktrbr** [Nastyaturysheva/Education#1]
## Функция принимает на вход

- [x] Целое число (int) -- сам год, который нужно проверить

## Функция должна сделать

- [x] Напечатать какой год (високосный или нет)
- [x] И напечатать почему?

_Возвращать ничего не надо_ 

### Пример

**Входные данные:**
```
2400
```
**Выходные данные:**
```
2400 -- високосный год
Он делится на 400
```

**Comment by Nastyaturysheva** [comment]
https://github.com/Nastyaturysheva/Education/blob/92daf85248d2dfbedcc16686f46a9e624ea33be4/Function/lesson_1.py#L42-L54
